// Complete Product Catalog - FMCG, Electronics, Daily Essentials
// Sourced from Amazon, eBay, AliExpress, Meesho, Blinkit, Zepto, IndiaMART

export interface Product {
  id: string;
  name: string;
  keywords: string[];
  description: string;
  shortDescription: string;
  category: ProductCategory;
  subcategory: string;
  brand: string;
  source: ProductSource;
  
  // Pricing
  mrp: number; // Maximum Retail Price in INR
  sellingPrice: number; // Current selling price in INR
  costPrice: number; // Vendor cost price in INR
  margin: number; // Profit margin percentage
  
  // Images
  images: string[];
  thumbnail: string;
  
  // Inventory
  stock: number;
  sku: string;
  barcode?: string;
  
  // Ratings & Reviews
  rating: number;
  reviewCount: number;
  reviews: ProductReview[];
  
  // Sales Data
  totalSold: number;
  weeklySold: number;
  dailySold: number;
  
  // Shipping
  weight: number; // in grams
  dimensions: { length: number; width: number; height: number }; // in cm
  freeShipping: boolean;
  deliveryDays: number;
  
  // Vendor
  vendorId: string;
  vendorName: string;
  vendorRating: number;
  
  // Status
  isActive: boolean;
  isFeatured: boolean;
  isDailyDeal: boolean;
  dealEndTime?: Date;
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

export interface ProductReview {
  id: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  rating: number;
  title: string;
  comment: string;
  images?: string[];
  helpful: number;
  verified: boolean;
  createdAt: Date;
}

export type ProductCategory = 
  | 'groceries'
  | 'dairy'
  | 'fruits-vegetables'
  | 'beverages'
  | 'snacks'
  | 'personal-care'
  | 'household'
  | 'electronics'
  | 'mobile-accessories'
  | 'computer-accessories'
  | 'home-kitchen'
  | 'baby-care'
  | 'pet-supplies'
  | 'health-wellness'
  | 'fashion';

export type ProductSource = 
  | 'amazon' 
  | 'ebay' 
  | 'aliexpress' 
  | 'meesho' 
  | 'blinkit' 
  | 'zepto' 
  | 'indiamart' 
  | 'shopify';

// Mock product images using placeholder
const getProductImage = (category: string, index: number): string => {
  const seed = `${category}-${index}`;
  return `https://picsum.photos/seed/${seed}/400/400`;
};

// Generate mock reviews
const generateReviews = (productName: string, count: number, avgRating: number): ProductReview[] => {
  const reviews: ProductReview[] = [];
  const names = ['Rajesh K.', 'Priya S.', 'Amit P.', 'Sneha R.', 'Vikram M.', 'Anita D.', 'Suresh B.', 'Kavita T.', 'Rahul G.', 'Meena J.'];
  const titles = ['Great product!', 'Value for money', 'Good quality', 'Fast delivery', 'Satisfied', 'Recommended', 'Excellent', 'Nice product', 'Happy with purchase', 'Will buy again'];
  const comments = [
    'The product quality is excellent and delivery was on time. Highly recommended!',
    'Good value for the price. Works as expected. Happy with my purchase.',
    'Quality product at a reasonable price. The packaging was also good.',
    'Fast delivery and the product matches the description perfectly.',
    'Been using this for a week now, absolutely love it!',
    'Great product for daily use. Worth every rupee spent.',
    'The quality exceeded my expectations. Will definitely order again.',
    'Perfect for my needs. Good build quality and works flawlessly.',
    'Arrived earlier than expected. Product is exactly as shown.',
    'Best in this price range. Compared with other brands and this wins.',
  ];

  for (let i = 0; i < count; i++) {
    const ratingVariance = Math.random() > 0.7 ? -1 : (Math.random() > 0.5 ? 0 : 1);
    const rating = Math.max(1, Math.min(5, Math.round(avgRating + ratingVariance)));
    
    reviews.push({
      id: `REV${Date.now()}${i}`,
      userId: `USR${Math.random().toString(36).substr(2, 6).toUpperCase()}`,
      userName: names[Math.floor(Math.random() * names.length)],
      rating,
      title: titles[Math.floor(Math.random() * titles.length)],
      comment: comments[Math.floor(Math.random() * comments.length)],
      helpful: Math.floor(Math.random() * 50) + 1,
      verified: Math.random() > 0.2,
      createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
    });
  }

  return reviews;
};

// Complete Product Database
export const PRODUCTS: Product[] = [
  // ============ GROCERIES ============
  {
    id: 'PROD001',
    name: 'Aashirvaad Atta - Whole Wheat Flour',
    keywords: ['atta', 'flour', 'wheat', 'aashirvaad', 'chapati', 'roti'],
    description: 'Aashirvaad Whole Wheat Atta is made from the finest quality wheat grains. It is 100% pure and contains 0% maida. The atta is perfect for making soft and fluffy rotis, parathas, and other Indian breads. Contains natural dietary fiber and essential nutrients for a healthy diet.',
    shortDescription: 'Premium quality whole wheat flour for soft rotis and parathas',
    category: 'groceries',
    subcategory: 'Flour & Grains',
    brand: 'Aashirvaad',
    source: 'blinkit',
    mrp: 299,
    sellingPrice: 275,
    costPrice: 220,
    margin: 20,
    images: [getProductImage('atta', 1), getProductImage('atta', 2), getProductImage('atta', 3)],
    thumbnail: getProductImage('atta', 1),
    stock: 150,
    sku: 'AASH-ATTA-5KG',
    rating: 4.5,
    reviewCount: 2340,
    reviews: generateReviews('Aashirvaad Atta', 15, 4.5),
    totalSold: 15420,
    weeklySold: 892,
    dailySold: 127,
    weight: 5000,
    dimensions: { length: 25, width: 18, height: 10 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD002',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    keywords: ['sunflower oil', 'cooking oil', 'refined oil', 'fortune', 'healthy oil'],
    description: 'Fortune Sunlite Refined Sunflower Oil is enriched with vitamins A, D, and E. It has a light texture and neutral taste that preserves the natural flavor of your food. Low in saturated fats and high in polyunsaturated fats, making it a heart-healthy choice.',
    shortDescription: 'Light and healthy refined sunflower oil for everyday cooking',
    category: 'groceries',
    subcategory: 'Oils & Ghee',
    brand: 'Fortune',
    source: 'zepto',
    mrp: 189,
    sellingPrice: 175,
    costPrice: 145,
    margin: 17,
    images: [getProductImage('oil', 1), getProductImage('oil', 2)],
    thumbnail: getProductImage('oil', 1),
    stock: 200,
    sku: 'FORT-OIL-1L',
    rating: 4.3,
    reviewCount: 1856,
    reviews: generateReviews('Fortune Oil', 12, 4.3),
    totalSold: 12350,
    weeklySold: 654,
    dailySold: 93,
    weight: 950,
    dimensions: { length: 12, width: 8, height: 26 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD003',
    name: 'Tata Salt - Iodized Salt',
    keywords: ['salt', 'iodized', 'tata', 'cooking salt', 'namak'],
    description: 'Tata Salt is India\'s most trusted iodized salt brand. It contains the right amount of iodine essential for proper growth and development. Vacuum evaporated and hygienically packed to ensure purity and quality.',
    shortDescription: 'Pure iodized salt for daily cooking needs',
    category: 'groceries',
    subcategory: 'Spices & Salt',
    brand: 'Tata',
    source: 'blinkit',
    mrp: 24,
    sellingPrice: 22,
    costPrice: 18,
    margin: 18,
    images: [getProductImage('salt', 1)],
    thumbnail: getProductImage('salt', 1),
    stock: 500,
    sku: 'TATA-SALT-1KG',
    rating: 4.7,
    reviewCount: 4523,
    reviews: generateReviews('Tata Salt', 20, 4.7),
    totalSold: 45670,
    weeklySold: 2340,
    dailySold: 334,
    weight: 1000,
    dimensions: { length: 15, width: 10, height: 5 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD004',
    name: 'India Gate Basmati Rice - Classic',
    keywords: ['basmati rice', 'rice', 'india gate', 'long grain', 'biryani rice'],
    description: 'India Gate Classic Basmati Rice features extra-long grains that elongate to almost double their size upon cooking. Aged to perfection for superior taste and aroma. Ideal for biryani, pulao, and other rice dishes.',
    shortDescription: 'Premium aged basmati rice with extra-long grains',
    category: 'groceries',
    subcategory: 'Rice & Rice Products',
    brand: 'India Gate',
    source: 'amazon',
    mrp: 399,
    sellingPrice: 365,
    costPrice: 295,
    margin: 19,
    images: [getProductImage('rice', 1), getProductImage('rice', 2)],
    thumbnail: getProductImage('rice', 1),
    stock: 120,
    sku: 'IGATE-RICE-5KG',
    rating: 4.6,
    reviewCount: 3210,
    reviews: generateReviews('India Gate Rice', 18, 4.6),
    totalSold: 18920,
    weeklySold: 1120,
    dailySold: 160,
    weight: 5000,
    dimensions: { length: 30, width: 20, height: 12 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD005',
    name: 'Toor Dal - Premium Quality',
    keywords: ['toor dal', 'pigeon pea', 'dal', 'lentils', 'arhar dal'],
    description: 'Premium quality Toor Dal (Pigeon Pea) sourced from the best farms. Rich in protein, dietary fiber, and essential nutrients. Easy to cook and perfect for making delicious dal tadka, sambar, and other lentil dishes.',
    shortDescription: 'High-protein toor dal for delicious lentil dishes',
    category: 'groceries',
    subcategory: 'Pulses & Lentils',
    brand: 'BRAVE Essentials',
    source: 'indiamart',
    mrp: 175,
    sellingPrice: 159,
    costPrice: 125,
    margin: 21,
    images: [getProductImage('dal', 1)],
    thumbnail: getProductImage('dal', 1),
    stock: 180,
    sku: 'BRAVE-TOOR-1KG',
    rating: 4.4,
    reviewCount: 1245,
    reviews: generateReviews('Toor Dal', 10, 4.4),
    totalSold: 8920,
    weeklySold: 523,
    dailySold: 75,
    weight: 1000,
    dimensions: { length: 18, width: 12, height: 6 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },

  // ============ DAIRY ============
  {
    id: 'PROD006',
    name: 'Amul Gold Full Cream Milk',
    keywords: ['milk', 'amul', 'full cream', 'dairy', 'fresh milk'],
    description: 'Amul Gold Full Cream Milk is fresh, pure, and nutritious. Contains 6% fat and 9% SNF (Solids Not Fat). Perfect for drinking, making tea, coffee, curd, and sweets. Sourced from the best dairy farms.',
    shortDescription: 'Fresh full cream milk with 6% fat content',
    category: 'dairy',
    subcategory: 'Milk',
    brand: 'Amul',
    source: 'zepto',
    mrp: 68,
    sellingPrice: 68,
    costPrice: 58,
    margin: 15,
    images: [getProductImage('milk', 1)],
    thumbnail: getProductImage('milk', 1),
    stock: 300,
    sku: 'AMUL-MILK-1L',
    rating: 4.8,
    reviewCount: 5670,
    reviews: generateReviews('Amul Milk', 25, 4.8),
    totalSold: 56780,
    weeklySold: 4560,
    dailySold: 651,
    weight: 1030,
    dimensions: { length: 10, width: 10, height: 20 },
    freeShipping: true,
    deliveryDays: 0,
    vendorId: 'VND002',
    vendorName: 'BRAVE Dairy Fresh',
    vendorRating: 4.9,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD007',
    name: 'Amul Butter - 500g',
    keywords: ['butter', 'amul', 'dairy', 'toast', 'cooking butter'],
    description: 'Amul Butter is made from fresh cream and has a rich, creamy taste. Perfect for spreading on toast, parathas, or for cooking and baking. Contains 80% milk fat for authentic buttery flavor.',
    shortDescription: 'Rich creamy butter for spreading and cooking',
    category: 'dairy',
    subcategory: 'Butter & Cheese',
    brand: 'Amul',
    source: 'blinkit',
    mrp: 285,
    sellingPrice: 270,
    costPrice: 230,
    margin: 15,
    images: [getProductImage('butter', 1)],
    thumbnail: getProductImage('butter', 1),
    stock: 100,
    sku: 'AMUL-BUTTER-500G',
    rating: 4.9,
    reviewCount: 8234,
    reviews: generateReviews('Amul Butter', 30, 4.9),
    totalSold: 67890,
    weeklySold: 5230,
    dailySold: 747,
    weight: 500,
    dimensions: { length: 15, width: 8, height: 4 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND002',
    vendorName: 'BRAVE Dairy Fresh',
    vendorRating: 4.9,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD008',
    name: 'Amul Cheese Slices',
    keywords: ['cheese', 'amul', 'cheese slices', 'sandwich', 'burger'],
    description: 'Amul Cheese Slices are perfect for sandwiches, burgers, and snacks. Made from high-quality milk with a smooth, creamy texture. Each slice is individually wrapped for freshness.',
    shortDescription: 'Creamy cheese slices for sandwiches and burgers',
    category: 'dairy',
    subcategory: 'Butter & Cheese',
    brand: 'Amul',
    source: 'zepto',
    mrp: 149,
    sellingPrice: 139,
    costPrice: 115,
    margin: 17,
    images: [getProductImage('cheese', 1)],
    thumbnail: getProductImage('cheese', 1),
    stock: 150,
    sku: 'AMUL-CHEESE-200G',
    rating: 4.6,
    reviewCount: 3421,
    reviews: generateReviews('Amul Cheese', 15, 4.6),
    totalSold: 23450,
    weeklySold: 1560,
    dailySold: 223,
    weight: 200,
    dimensions: { length: 18, width: 12, height: 2 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND002',
    vendorName: 'BRAVE Dairy Fresh',
    vendorRating: 4.9,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD009',
    name: 'Mother Dairy Curd - Fresh Dahi',
    keywords: ['curd', 'dahi', 'yogurt', 'mother dairy', 'fresh curd'],
    description: 'Mother Dairy Fresh Curd is thick, creamy, and delicious. Made from pure milk with active cultures for gut health. Perfect for making raita, lassi, or enjoying as is.',
    shortDescription: 'Thick creamy curd for raita, lassi, and more',
    category: 'dairy',
    subcategory: 'Curd & Yogurt',
    brand: 'Mother Dairy',
    source: 'blinkit',
    mrp: 55,
    sellingPrice: 52,
    costPrice: 42,
    margin: 19,
    images: [getProductImage('curd', 1)],
    thumbnail: getProductImage('curd', 1),
    stock: 200,
    sku: 'MD-CURD-1KG',
    rating: 4.5,
    reviewCount: 2890,
    reviews: generateReviews('Mother Dairy Curd', 12, 4.5),
    totalSold: 34210,
    weeklySold: 2340,
    dailySold: 334,
    weight: 1000,
    dimensions: { length: 12, width: 12, height: 8 },
    freeShipping: true,
    deliveryDays: 0,
    vendorId: 'VND002',
    vendorName: 'BRAVE Dairy Fresh',
    vendorRating: 4.9,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },

  // ============ ELECTRONICS ============
  {
    id: 'PROD010',
    name: 'boAt Bassheads 100 Wired Earphones',
    keywords: ['earphones', 'wired', 'boat', 'headphones', 'bass', 'music'],
    description: 'boAt Bassheads 100 in-ear wired earphones with powerful bass and crystal clear sound. Features 10mm dynamic drivers, integrated microphone, and tangle-free cable. Compatible with all 3.5mm jack devices.',
    shortDescription: 'Powerful bass wired earphones with mic',
    category: 'electronics',
    subcategory: 'Audio',
    brand: 'boAt',
    source: 'amazon',
    mrp: 799,
    sellingPrice: 399,
    costPrice: 180,
    margin: 55,
    images: [getProductImage('earphones', 1), getProductImage('earphones', 2)],
    thumbnail: getProductImage('earphones', 1),
    stock: 500,
    sku: 'BOAT-BH100',
    rating: 4.2,
    reviewCount: 156789,
    reviews: generateReviews('boAt Earphones', 50, 4.2),
    totalSold: 892340,
    weeklySold: 12340,
    dailySold: 1763,
    weight: 50,
    dimensions: { length: 15, width: 10, height: 3 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD011',
    name: 'Mi Power Bank 20000mAh',
    keywords: ['power bank', 'mi', 'xiaomi', 'charger', 'portable charger', 'battery'],
    description: 'Mi Power Bank 2i with 20000mAh capacity features 18W fast charging, dual output ports, and power delivery support. Charge two devices simultaneously with intelligent power management.',
    shortDescription: '20000mAh fast charging power bank',
    category: 'electronics',
    subcategory: 'Power Banks',
    brand: 'Mi',
    source: 'amazon',
    mrp: 1499,
    sellingPrice: 1299,
    costPrice: 850,
    margin: 35,
    images: [getProductImage('powerbank', 1), getProductImage('powerbank', 2)],
    thumbnail: getProductImage('powerbank', 1),
    stock: 150,
    sku: 'MI-PB20K',
    rating: 4.4,
    reviewCount: 89340,
    reviews: generateReviews('Mi Power Bank', 40, 4.4),
    totalSold: 456780,
    weeklySold: 6780,
    dailySold: 969,
    weight: 350,
    dimensions: { length: 15, width: 7, height: 3 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD012',
    name: 'JBL Go 2 Portable Bluetooth Speaker',
    keywords: ['speaker', 'bluetooth', 'jbl', 'portable', 'wireless speaker', 'music'],
    description: 'JBL Go 2 is a waterproof portable Bluetooth speaker with powerful sound. Features 5 hours of playtime, speakerphone, and IPX7 waterproof rating. Compact design perfect for on-the-go.',
    shortDescription: 'Waterproof portable Bluetooth speaker',
    category: 'electronics',
    subcategory: 'Audio',
    brand: 'JBL',
    source: 'amazon',
    mrp: 3499,
    sellingPrice: 2799,
    costPrice: 1800,
    margin: 36,
    images: [getProductImage('speaker', 1), getProductImage('speaker', 2)],
    thumbnail: getProductImage('speaker', 1),
    stock: 80,
    sku: 'JBL-GO2',
    rating: 4.5,
    reviewCount: 45678,
    reviews: generateReviews('JBL Go 2', 35, 4.5),
    totalSold: 234560,
    weeklySold: 3450,
    dailySold: 493,
    weight: 184,
    dimensions: { length: 8, width: 7, height: 3 },
    freeShipping: true,
    deliveryDays: 3,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD013',
    name: 'SanDisk Ultra 64GB USB 3.0 Pen Drive',
    keywords: ['pendrive', 'usb', 'sandisk', 'flash drive', 'storage', '64gb'],
    description: 'SanDisk Ultra 64GB USB 3.0 Flash Drive offers high-speed data transfer up to 100MB/s. Durable metal casing, password protection, and recovery software included. Backward compatible with USB 2.0.',
    shortDescription: 'High-speed 64GB USB 3.0 flash drive',
    category: 'electronics',
    subcategory: 'Storage',
    brand: 'SanDisk',
    source: 'amazon',
    mrp: 899,
    sellingPrice: 549,
    costPrice: 320,
    margin: 42,
    images: [getProductImage('pendrive', 1)],
    thumbnail: getProductImage('pendrive', 1),
    stock: 300,
    sku: 'SAND-USB64',
    rating: 4.6,
    reviewCount: 67890,
    reviews: generateReviews('SanDisk Pen Drive', 30, 4.6),
    totalSold: 345670,
    weeklySold: 4890,
    dailySold: 699,
    weight: 15,
    dimensions: { length: 5, width: 2, height: 1 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 5 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD014',
    name: 'TP-Link WiFi Router Archer C6',
    keywords: ['router', 'wifi', 'tp-link', 'wireless', 'dual band', 'internet'],
    description: 'TP-Link Archer C6 AC1200 Dual Band WiFi Router with 4 antennas and MU-MIMO technology. Supports speeds up to 867Mbps (5GHz) + 300Mbps (2.4GHz). Guest network and parental controls included.',
    shortDescription: 'Dual band AC1200 WiFi router with 4 antennas',
    category: 'electronics',
    subcategory: 'Networking',
    brand: 'TP-Link',
    source: 'amazon',
    mrp: 2999,
    sellingPrice: 2199,
    costPrice: 1400,
    margin: 36,
    images: [getProductImage('router', 1), getProductImage('router', 2)],
    thumbnail: getProductImage('router', 1),
    stock: 60,
    sku: 'TPLINK-C6',
    rating: 4.3,
    reviewCount: 34560,
    reviews: generateReviews('TP-Link Router', 25, 4.3),
    totalSold: 178900,
    weeklySold: 2340,
    dailySold: 334,
    weight: 450,
    dimensions: { length: 23, width: 14, height: 4 },
    freeShipping: true,
    deliveryDays: 3,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date(),
  },

  // ============ MOBILE ACCESSORIES ============
  {
    id: 'PROD015',
    name: 'Spigen Tough Armor iPhone Case',
    keywords: ['iphone case', 'spigen', 'phone cover', 'protective case', 'iphone'],
    description: 'Spigen Tough Armor case provides military-grade protection with dual-layer design. Features Air Cushion Technology, built-in kickstand, and precise cutouts. Compatible with iPhone 14 Pro Max.',
    shortDescription: 'Military-grade protective case with kickstand',
    category: 'mobile-accessories',
    subcategory: 'Phone Cases',
    brand: 'Spigen',
    source: 'amazon',
    mrp: 1499,
    sellingPrice: 999,
    costPrice: 550,
    margin: 45,
    images: [getProductImage('case', 1), getProductImage('case', 2)],
    thumbnail: getProductImage('case', 1),
    stock: 120,
    sku: 'SPIG-IP14PM',
    rating: 4.6,
    reviewCount: 23450,
    reviews: generateReviews('Spigen Case', 20, 4.6),
    totalSold: 145670,
    weeklySold: 2120,
    dailySold: 303,
    weight: 80,
    dimensions: { length: 17, width: 9, height: 2 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD016',
    name: 'Anker PowerPort III 65W Fast Charger',
    keywords: ['charger', 'anker', 'fast charger', '65w', 'usb-c', 'gan'],
    description: 'Anker PowerPort III 65W charger with GaN technology. Compact design with PowerIQ 3.0 for universal compatibility. Charge laptops, tablets, and phones at maximum speed.',
    shortDescription: 'Compact 65W GaN fast charger',
    category: 'mobile-accessories',
    subcategory: 'Chargers',
    brand: 'Anker',
    source: 'amazon',
    mrp: 3499,
    sellingPrice: 2799,
    costPrice: 1800,
    margin: 36,
    images: [getProductImage('charger', 1)],
    thumbnail: getProductImage('charger', 1),
    stock: 75,
    sku: 'ANKER-65W',
    rating: 4.7,
    reviewCount: 15670,
    reviews: generateReviews('Anker Charger', 18, 4.7),
    totalSold: 89030,
    weeklySold: 1230,
    dailySold: 176,
    weight: 150,
    dimensions: { length: 6, width: 6, height: 3 },
    freeShipping: true,
    deliveryDays: 3,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD017',
    name: 'Samsung Type-C Cable 1.5m',
    keywords: ['usb cable', 'type-c', 'samsung', 'charging cable', 'fast charging'],
    description: 'Original Samsung USB Type-C cable supports fast charging and data transfer up to 480Mbps. Durable braided design with 1.5m length. Compatible with Samsung Galaxy, Pixel, and other Type-C devices.',
    shortDescription: 'Original Samsung Type-C fast charging cable',
    category: 'mobile-accessories',
    subcategory: 'Cables',
    brand: 'Samsung',
    source: 'amazon',
    mrp: 899,
    sellingPrice: 499,
    costPrice: 220,
    margin: 56,
    images: [getProductImage('cable', 1)],
    thumbnail: getProductImage('cable', 1),
    stock: 400,
    sku: 'SAM-USBC15',
    rating: 4.3,
    reviewCount: 45670,
    reviews: generateReviews('Samsung Cable', 25, 4.3),
    totalSold: 267890,
    weeklySold: 3890,
    dailySold: 556,
    weight: 40,
    dimensions: { length: 15, width: 8, height: 2 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND003',
    vendorName: 'BRAVE Electronics Hub',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 3 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },

  // ============ BEVERAGES ============
  {
    id: 'PROD018',
    name: 'Tata Gold Tea - Premium Blend',
    keywords: ['tea', 'tata', 'chai', 'premium tea', 'assam tea'],
    description: 'Tata Gold Premium Tea is a rich blend of Assam tea leaves with a distinct aroma and strong taste. Perfect for making authentic Indian chai with milk. 85% strong Assam CTC and 15% long leaves.',
    shortDescription: 'Premium Assam tea blend for strong chai',
    category: 'beverages',
    subcategory: 'Tea',
    brand: 'Tata',
    source: 'blinkit',
    mrp: 280,
    sellingPrice: 265,
    costPrice: 210,
    margin: 21,
    images: [getProductImage('tea', 1)],
    thumbnail: getProductImage('tea', 1),
    stock: 200,
    sku: 'TATA-GOLD-500G',
    rating: 4.6,
    reviewCount: 12340,
    reviews: generateReviews('Tata Tea', 18, 4.6),
    totalSold: 56780,
    weeklySold: 3450,
    dailySold: 493,
    weight: 500,
    dimensions: { length: 15, width: 10, height: 8 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD019',
    name: 'Nescafé Classic Instant Coffee',
    keywords: ['coffee', 'nescafe', 'instant coffee', 'nescafe classic', 'caffeine'],
    description: 'Nescafé Classic is the world\'s most loved instant coffee. Made from carefully selected coffee beans, roasted to perfection for a rich, aromatic taste. Quick and easy to prepare.',
    shortDescription: 'Classic instant coffee for rich aroma',
    category: 'beverages',
    subcategory: 'Coffee',
    brand: 'Nescafé',
    source: 'zepto',
    mrp: 290,
    sellingPrice: 275,
    costPrice: 220,
    margin: 20,
    images: [getProductImage('coffee', 1)],
    thumbnail: getProductImage('coffee', 1),
    stock: 180,
    sku: 'NESCAFE-100G',
    rating: 4.5,
    reviewCount: 18790,
    reviews: generateReviews('Nescafé', 20, 4.5),
    totalSold: 78450,
    weeklySold: 4560,
    dailySold: 651,
    weight: 100,
    dimensions: { length: 10, width: 8, height: 12 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD020',
    name: 'Real Fruit Juice - Mixed Fruit',
    keywords: ['juice', 'real', 'fruit juice', 'mixed fruit', 'beverage'],
    description: 'Real Mixed Fruit Juice is made from the best quality fruits with no added preservatives. Contains fruit pulp for authentic taste. Rich in vitamins and natural fruit goodness.',
    shortDescription: 'Preservative-free mixed fruit juice',
    category: 'beverages',
    subcategory: 'Juices',
    brand: 'Real',
    source: 'blinkit',
    mrp: 110,
    sellingPrice: 99,
    costPrice: 75,
    margin: 24,
    images: [getProductImage('juice', 1)],
    thumbnail: getProductImage('juice', 1),
    stock: 250,
    sku: 'REAL-MIX-1L',
    rating: 4.4,
    reviewCount: 8760,
    reviews: generateReviews('Real Juice', 15, 4.4),
    totalSold: 45670,
    weeklySold: 2890,
    dailySold: 413,
    weight: 1050,
    dimensions: { length: 10, width: 8, height: 22 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 7 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },

  // ============ PERSONAL CARE ============
  {
    id: 'PROD021',
    name: 'Dove Moisturising Beauty Bar',
    keywords: ['soap', 'dove', 'moisturising', 'beauty bar', 'skincare'],
    description: 'Dove Beauty Bar contains 1/4 moisturizing cream that nourishes skin while cleansing. Gentle formula is suitable for daily use on all skin types. Leaves skin soft, smooth, and radiant.',
    shortDescription: 'Moisturizing beauty bar for soft skin',
    category: 'personal-care',
    subcategory: 'Bath & Body',
    brand: 'Dove',
    source: 'amazon',
    mrp: 180,
    sellingPrice: 165,
    costPrice: 120,
    margin: 27,
    images: [getProductImage('soap', 1)],
    thumbnail: getProductImage('soap', 1),
    stock: 300,
    sku: 'DOVE-BAR-100G',
    rating: 4.6,
    reviewCount: 23450,
    reviews: generateReviews('Dove', 22, 4.6),
    totalSold: 123450,
    weeklySold: 7120,
    dailySold: 1017,
    weight: 100,
    dimensions: { length: 8, width: 5, height: 3 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD022',
    name: 'Colgate Strong Teeth Toothpaste',
    keywords: ['toothpaste', 'colgate', 'dental', 'teeth', 'oral care'],
    description: 'Colgate Strong Teeth toothpaste provides cavity protection and strengthens teeth with fluoride. Fresh mint flavor for long-lasting fresh breath. Recommended by dentists worldwide.',
    shortDescription: 'Cavity protection toothpaste with fluoride',
    category: 'personal-care',
    subcategory: 'Oral Care',
    brand: 'Colgate',
    source: 'blinkit',
    mrp: 95,
    sellingPrice: 88,
    costPrice: 62,
    margin: 30,
    images: [getProductImage('toothpaste', 1)],
    thumbnail: getProductImage('toothpaste', 1),
    stock: 400,
    sku: 'COLG-ST-150G',
    rating: 4.5,
    reviewCount: 34560,
    reviews: generateReviews('Colgate', 25, 4.5),
    totalSold: 234560,
    weeklySold: 12340,
    dailySold: 1763,
    weight: 150,
    dimensions: { length: 20, width: 5, height: 4 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD023',
    name: 'Himalaya Face Wash - Neem',
    keywords: ['face wash', 'himalaya', 'neem', 'acne', 'skincare', 'face cleanser'],
    description: 'Himalaya Neem Face Wash is a herbal formulation that gently cleanses and fights acne. Contains neem and turmeric for their antibacterial properties. Suitable for oily and acne-prone skin.',
    shortDescription: 'Herbal face wash for acne-prone skin',
    category: 'personal-care',
    subcategory: 'Face Care',
    brand: 'Himalaya',
    source: 'amazon',
    mrp: 195,
    sellingPrice: 175,
    costPrice: 120,
    margin: 31,
    images: [getProductImage('facewash', 1)],
    thumbnail: getProductImage('facewash', 1),
    stock: 250,
    sku: 'HIMA-NEEM-100ML',
    rating: 4.4,
    reviewCount: 45670,
    reviews: generateReviews('Himalaya Face Wash', 30, 4.4),
    totalSold: 289340,
    weeklySold: 15670,
    dailySold: 2239,
    weight: 120,
    dimensions: { length: 6, width: 6, height: 15 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD024',
    name: 'Head & Shoulders Anti-Dandruff Shampoo',
    keywords: ['shampoo', 'head and shoulders', 'anti dandruff', 'hair care', 'dandruff'],
    description: 'Head & Shoulders Anti-Dandruff Shampoo provides up to 100% dandruff protection. Gentle formula cleanses scalp and leaves hair soft and manageable. Fresh scent for all-day freshness.',
    shortDescription: 'Anti-dandruff shampoo for clean scalp',
    category: 'personal-care',
    subcategory: 'Hair Care',
    brand: 'Head & Shoulders',
    source: 'amazon',
    mrp: 399,
    sellingPrice: 349,
    costPrice: 240,
    margin: 31,
    images: [getProductImage('shampoo', 1)],
    thumbnail: getProductImage('shampoo', 1),
    stock: 180,
    sku: 'HNS-ANTI-340ML',
    rating: 4.5,
    reviewCount: 34560,
    reviews: generateReviews('Head & Shoulders', 22, 4.5),
    totalSold: 198760,
    weeklySold: 11230,
    dailySold: 1604,
    weight: 380,
    dimensions: { length: 8, width: 8, height: 22 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },

  // ============ HOUSEHOLD ============
  {
    id: 'PROD025',
    name: 'Surf Excel Easy Wash Detergent',
    keywords: ['detergent', 'surf excel', 'washing powder', 'laundry', 'clothes'],
    description: 'Surf Excel Easy Wash detergent removes tough stains easily. Its unique formula works on colored and white clothes. Hand wash and machine wash compatible.',
    shortDescription: 'Powerful detergent for tough stain removal',
    category: 'household',
    subcategory: 'Laundry',
    brand: 'Surf Excel',
    source: 'blinkit',
    mrp: 215,
    sellingPrice: 199,
    costPrice: 155,
    margin: 22,
    images: [getProductImage('detergent', 1)],
    thumbnail: getProductImage('detergent', 1),
    stock: 200,
    sku: 'SURF-EW-1KG',
    rating: 4.6,
    reviewCount: 28900,
    reviews: generateReviews('Surf Excel', 18, 4.6),
    totalSold: 167890,
    weeklySold: 9340,
    dailySold: 1334,
    weight: 1000,
    dimensions: { length: 20, width: 15, height: 8 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND005',
    vendorName: 'BRAVE Household Supplies',
    vendorRating: 4.5,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD026',
    name: 'Vim Liquid Dishwash',
    keywords: ['dishwash', 'vim', 'dish soap', 'kitchen', 'utensils'],
    description: 'Vim Liquid Dishwash cuts through tough grease and food residue easily. Contains lemon power for fresh fragrance and spotless shine. Gentle on hands, tough on grease.',
    shortDescription: 'Lemon-powered dishwash for spotless utensils',
    category: 'household',
    subcategory: 'Kitchen Cleaning',
    brand: 'Vim',
    source: 'zepto',
    mrp: 95,
    sellingPrice: 88,
    costPrice: 65,
    margin: 26,
    images: [getProductImage('dishwash', 1)],
    thumbnail: getProductImage('dishwash', 1),
    stock: 350,
    sku: 'VIM-LIQ-500ML',
    rating: 4.5,
    reviewCount: 23450,
    reviews: generateReviews('Vim', 15, 4.5),
    totalSold: 145670,
    weeklySold: 7890,
    dailySold: 1127,
    weight: 550,
    dimensions: { length: 8, width: 8, height: 18 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND005',
    vendorName: 'BRAVE Household Supplies',
    vendorRating: 4.5,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD027',
    name: 'Lizol Floor Cleaner - Citrus',
    keywords: ['floor cleaner', 'lizol', 'disinfectant', 'cleaning', 'household'],
    description: 'Lizol Floor Cleaner kills 99.9% germs and leaves floors sparkling clean. Fresh citrus fragrance lasts for hours. Suitable for all floor types including marble and tiles.',
    shortDescription: 'Germ-killing floor cleaner with citrus fragrance',
    category: 'household',
    subcategory: 'Floor Cleaning',
    brand: 'Lizol',
    source: 'blinkit',
    mrp: 140,
    sellingPrice: 129,
    costPrice: 95,
    margin: 26,
    images: [getProductImage('cleaner', 1)],
    thumbnail: getProductImage('cleaner', 1),
    stock: 280,
    sku: 'LIZOL-CIT-1L',
    rating: 4.4,
    reviewCount: 16780,
    reviews: generateReviews('Lizol', 12, 4.4),
    totalSold: 98760,
    weeklySold: 5670,
    dailySold: 810,
    weight: 1050,
    dimensions: { length: 10, width: 8, height: 25 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND005',
    vendorName: 'BRAVE Household Supplies',
    vendorRating: 4.5,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date(),
  },

  // ============ SNACKS ============
  {
    id: 'PROD028',
    name: 'Lay\'s Classic Salted Chips',
    keywords: ['chips', 'lays', 'potato chips', 'snacks', 'salted'],
    description: 'Lay\'s Classic Salted potato chips are thin, crispy, and perfectly salted. Made from farm-grown potatoes with irresistible taste. Perfect snack for any time of day.',
    shortDescription: 'Classic salted potato chips',
    category: 'snacks',
    subcategory: 'Chips & Wafers',
    brand: 'Lay\'s',
    source: 'blinkit',
    mrp: 20,
    sellingPrice: 18,
    costPrice: 12,
    margin: 33,
    images: [getProductImage('chips', 1)],
    thumbnail: getProductImage('chips', 1),
    stock: 500,
    sku: 'LAYS-CLASS-28G',
    rating: 4.5,
    reviewCount: 45670,
    reviews: generateReviews('Lays', 20, 4.5),
    totalSold: 345670,
    weeklySold: 18900,
    dailySold: 2700,
    weight: 28,
    dimensions: { length: 15, width: 10, height: 2 },
    freeShipping: false,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD029',
    name: 'Parle-G Biscuits',
    keywords: ['biscuit', 'parle-g', 'cookies', 'snacks', 'tea time'],
    description: 'Parle-G is India\'s favorite glucose biscuit. Perfect for dipping in tea or enjoying as a quick snack. Contains glucose for energy and is fortified with vitamins.',
    shortDescription: 'Classic glucose biscuits for tea time',
    category: 'snacks',
    subcategory: 'Biscuits & Cookies',
    brand: 'Parle',
    source: 'blinkit',
    mrp: 10,
    sellingPrice: 10,
    costPrice: 7,
    margin: 30,
    images: [getProductImage('biscuit', 1)],
    thumbnail: getProductImage('biscuit', 1),
    stock: 600,
    sku: 'PARLE-G-56G',
    rating: 4.7,
    reviewCount: 56780,
    reviews: generateReviews('Parle-G', 25, 4.7),
    totalSold: 456890,
    weeklySold: 23450,
    dailySold: 3350,
    weight: 56,
    dimensions: { length: 12, width: 8, height: 3 },
    freeShipping: false,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD030',
    name: 'Maggi 2-Minute Noodles',
    keywords: ['maggi', 'noodles', 'instant noodles', 'snacks', 'quick meal'],
    description: 'Maggi 2-Minute Noodles is India\'s most loved instant noodle. Ready in just 2 minutes with the classic masala taste. Perfect for a quick meal or snack.',
    shortDescription: 'Classic masala instant noodles',
    category: 'snacks',
    subcategory: 'Instant Noodles',
    brand: 'Maggi',
    source: 'zepto',
    mrp: 14,
    sellingPrice: 13,
    costPrice: 9,
    margin: 31,
    images: [getProductImage('noodles', 1)],
    thumbnail: getProductImage('noodles', 1),
    stock: 700,
    sku: 'MAGGI-70G',
    rating: 4.8,
    reviewCount: 89012,
    reviews: generateReviews('Maggi', 35, 4.8),
    totalSold: 678900,
    weeklySold: 34560,
    dailySold: 4937,
    weight: 70,
    dimensions: { length: 12, width: 8, height: 4 },
    freeShipping: false,
    deliveryDays: 1,
    vendorId: 'VND001',
    vendorName: 'BRAVE FMCG Distribution',
    vendorRating: 4.8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 5 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },

  // ============ HOME KITCHEN ============
  {
    id: 'PROD031',
    name: 'Prestige Induction Cooktop',
    keywords: ['induction', 'prestige', 'cooktop', 'kitchen appliance', 'cooking'],
    description: 'Prestige Induction Cooktop with anti-magnetic wall and automatic voltage regulator. Features 2000W power consumption and intelligent power saving technology. Sleek design with easy touch controls.',
    shortDescription: '2000W induction cooktop with touch controls',
    category: 'home-kitchen',
    subcategory: 'Kitchen Appliances',
    brand: 'Prestige',
    source: 'amazon',
    mrp: 3995,
    sellingPrice: 2999,
    costPrice: 2100,
    margin: 30,
    images: [getProductImage('induction', 1), getProductImage('induction', 2)],
    thumbnail: getProductImage('induction', 1),
    stock: 40,
    sku: 'PREST-IND-2000',
    rating: 4.4,
    reviewCount: 23450,
    reviews: generateReviews('Prestige Induction', 18, 4.4),
    totalSold: 67890,
    weeklySold: 890,
    dailySold: 127,
    weight: 2500,
    dimensions: { length: 35, width: 28, height: 8 },
    freeShipping: true,
    deliveryDays: 4,
    vendorId: 'VND006',
    vendorName: 'BRAVE Home Appliances',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD032',
    name: 'Philips Air Fryer HD9202',
    keywords: ['air fryer', 'philips', 'kitchen appliance', 'healthy cooking', 'fryer'],
    description: 'Philips Air Fryer with Rapid Air Technology for healthier frying with up to 90% less fat. 4.1L capacity, adjustable temperature control, and easy-to-clean design.',
    shortDescription: 'Rapid Air Technology air fryer, 4.1L',
    category: 'home-kitchen',
    subcategory: 'Kitchen Appliances',
    brand: 'Philips',
    source: 'amazon',
    mrp: 8995,
    sellingPrice: 7299,
    costPrice: 5200,
    margin: 29,
    images: [getProductImage('airfryer', 1), getProductImage('airfryer', 2)],
    thumbnail: getProductImage('airfryer', 1),
    stock: 25,
    sku: 'PHIL-AF-HD9202',
    rating: 4.6,
    reviewCount: 12340,
    reviews: generateReviews('Philips Air Fryer', 15, 4.6),
    totalSold: 34560,
    weeklySold: 456,
    dailySold: 65,
    weight: 4500,
    dimensions: { length: 35, width: 30, height: 28 },
    freeShipping: true,
    deliveryDays: 4,
    vendorId: 'VND006',
    vendorName: 'BRAVE Home Appliances',
    vendorRating: 4.7,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    dealEndTime: new Date(Date.now() + 12 * 60 * 60 * 1000),
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date(),
  },

  // ============ HEALTH WELLNESS ============
  {
    id: 'PROD033',
    name: 'Dettol Antiseptic Liquid',
    keywords: ['dettol', 'antiseptic', 'disinfectant', 'first aid', 'germ protection'],
    description: 'Dettol Antiseptic Liquid provides protection from 100 illness-causing germs. Can be used for first aid, bathing, surface disinfection, and laundry. Trusted protection for over 80 years.',
    shortDescription: 'Antiseptic liquid for germ protection',
    category: 'health-wellness',
    subcategory: 'First Aid',
    brand: 'Dettol',
    source: 'blinkit',
    mrp: 85,
    sellingPrice: 78,
    costPrice: 55,
    margin: 29,
    images: [getProductImage('dettol', 1)],
    thumbnail: getProductImage('dettol', 1),
    stock: 400,
    sku: 'DETTOL-LIQ-250ML',
    rating: 4.7,
    reviewCount: 34560,
    reviews: generateReviews('Dettol', 20, 4.7),
    totalSold: 234560,
    weeklySold: 12340,
    dailySold: 1763,
    weight: 280,
    dimensions: { length: 6, width: 6, height: 16 },
    freeShipping: true,
    deliveryDays: 1,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD034',
    name: 'Himalaya Wellness Ashvagandha',
    keywords: ['ashwagandha', 'himalaya', 'supplement', 'stress relief', 'wellness'],
    description: 'Himalaya Ashvagandha is a natural stress reliever and rejuvenator. Helps reduce stress and anxiety, improves energy levels, and supports overall wellness. Pure herbal supplement.',
    shortDescription: 'Natural stress relief and energy supplement',
    category: 'health-wellness',
    subcategory: 'Supplements',
    brand: 'Himalaya',
    source: 'amazon',
    mrp: 250,
    sellingPrice: 225,
    costPrice: 160,
    margin: 29,
    images: [getProductImage('supplement', 1)],
    thumbnail: getProductImage('supplement', 1),
    stock: 150,
    sku: 'HIMA-ASH-60TAB',
    rating: 4.5,
    reviewCount: 8970,
    reviews: generateReviews('Himalaya Ashvagandha', 12, 4.5),
    totalSold: 45670,
    weeklySold: 2340,
    dailySold: 334,
    weight: 80,
    dimensions: { length: 10, width: 6, height: 6 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },

  // ============ BABY CARE ============
  {
    id: 'PROD035',
    name: 'Johnson\'s Baby Powder',
    keywords: ['baby powder', 'johnsons', 'baby care', 'talcum', 'infant'],
    description: 'Johnson\'s Baby Powder keeps baby\'s skin soft, smooth, and dry. Hypoallergenic formula tested for mildness. Classic baby fresh scent loved by generations.',
    shortDescription: 'Mild baby powder for soft skin',
    category: 'baby-care',
    subcategory: 'Baby Skin Care',
    brand: 'Johnson\'s',
    source: 'amazon',
    mrp: 175,
    sellingPrice: 159,
    costPrice: 115,
    margin: 28,
    images: [getProductImage('babypowder', 1)],
    thumbnail: getProductImage('babypowder', 1),
    stock: 200,
    sku: 'JOHN-POW-200G',
    rating: 4.6,
    reviewCount: 23450,
    reviews: generateReviews('Johnson\'s Baby Powder', 18, 4.6),
    totalSold: 145670,
    weeklySold: 7890,
    dailySold: 1127,
    weight: 200,
    dimensions: { length: 10, width: 10, height: 8 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date(),
  },
  {
    id: 'PROD036',
    name: 'Pampers Premium Care Pants',
    keywords: ['pampers', 'diapers', 'baby care', 'baby pants', 'infant'],
    description: 'Pampers Premium Care Pants provide up to 12 hours of dryness. Soft like cotton with a breathable outer cover. Easy to wear and remove with stretchable waistband.',
    shortDescription: 'Premium diaper pants with 12-hour protection',
    category: 'baby-care',
    subcategory: 'Diapers',
    brand: 'Pampers',
    source: 'amazon',
    mrp: 899,
    sellingPrice: 799,
    costPrice: 580,
    margin: 27,
    images: [getProductImage('diaper', 1)],
    thumbnail: getProductImage('diaper', 1),
    stock: 100,
    sku: 'PAMP-PREM-62',
    rating: 4.7,
    reviewCount: 34560,
    reviews: generateReviews('Pampers', 25, 4.7),
    totalSold: 178900,
    weeklySold: 9340,
    dailySold: 1334,
    weight: 800,
    dimensions: { length: 30, width: 20, height: 15 },
    freeShipping: true,
    deliveryDays: 2,
    vendorId: 'VND004',
    vendorName: 'BRAVE Personal Care',
    vendorRating: 4.6,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date(),
  },
];

// Helper functions
export function getProductsByCategory(category: ProductCategory): Product[] {
  return PRODUCTS.filter(p => p.category === category && p.isActive);
}

export function getProductsBySource(source: ProductSource): Product[] {
  return PRODUCTS.filter(p => p.source === source && p.isActive);
}

export function getDailyDeals(): Product[] {
  return PRODUCTS.filter(p => p.isDailyDeal && p.isActive && p.dealEndTime && new Date(p.dealEndTime) > new Date());
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.isFeatured && p.isActive);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return PRODUCTS.filter(p => 
    p.isActive && (
      p.name.toLowerCase().includes(lowerQuery) ||
      p.keywords.some(k => k.toLowerCase().includes(lowerQuery)) ||
      p.description.toLowerCase().includes(lowerQuery) ||
      p.brand.toLowerCase().includes(lowerQuery)
    )
  );
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id);
}

export function getProductsByVendor(vendorId: string): Product[] {
  return PRODUCTS.filter(p => p.vendorId === vendorId && p.isActive);
}

// Calculate deal discount
export function calculateDealDiscount(product: Product): number {
  if (!product.isDailyDeal) return 0;
  return Math.round(((product.mrp - product.sellingPrice) / product.mrp) * 100);
}

// Check if deal is active
export function isDealActive(product: Product): boolean {
  return product.isDailyDeal && !!product.dealEndTime && new Date(product.dealEndTime) > new Date();
}
